---
# We need sudo for some of the Docker commands.
sudo: required

env:
  # - distro: centos7
  #   init: /usr/lib/systemd/systemd
  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos6
    init: /sbin/init
    run_opts: ""
  # - distro: fedora24
  #   init: /usr/lib/systemd/systemd
  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - distro: ubuntu1604
  #   init: /lib/systemd/systemd
  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - distro: ubuntu1404
  #   init: /sbin/init
  #   run_opts: ""
  - distro: debian8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

before_install:
  # Pull container from Docker Hub.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  # Create a random file to store the container ID.
  - container_id=$(mktemp)

  # Run container detached, with our role mounted inside.
  - 'docker run --cap-add SYS_ADMIN --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'


  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test the Ansible role.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --diff'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


notifications:
  slack:
    secure: TfZJ6QqISTzMCelK3lyexSLyl66nPD+I/TVBWqGwmSKrbLgo5iGWgtwpBGt3HrM5Ke9LbZTDV6Q+XHM87kdPRYu/VEyY7JClfSHVJSi9WeF5ZC7AngkxbBXvnq5yTcn14EIqmb9PYbMtgWYTgbw309r86oyvm0TnqH+TXERaY/3AfVeo4Dczt/Fjq/FybqdsGSvRUgqR3bppZ/MRu4chnnt3DapP6U+srEL7qH2ltbYIQ6xkN+1PE7VyKYwez9iQXxH+nZVt/yLch0mB4h1Eax4FuIu9pgpv7LCdqNlGq1MGOQgSZHL3Llmc7//I1VI3ZWy3uHeirORXVN9pE8g75LRbOGSpQKNRccjhS33aXUC5MvlelVao8i8RajJIQrNQ9vr9T7hiEGOFRG3Yh4DBlcBeNGzI/YMURfAidUnI4JUA4pq+jWphS25MW5e6KylOFRMcDx5T6LlmRAJOvEVZr90toGSEO9kRzLw/vY89NuEbGBi6cZ4dLdhCSpwbjsF72RKa8DBOXat9vBYMQxHZONoIrOsq2rmrQoeNTAK2UV645ZEi7fGfuqYGmFI/x9w2CSGnYK0d4SyIe/CmBCUtwWYjPibAzMahWEX54Tupqo7l1AvGnYNxHql/Mfyp8t/v3E1T1zv10KpeGuOL9btCA4mNVEGy9jcKJVr0SN7VuzU=
